//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int sliderID { get; set; }
        public string baslikTR { get; set; }
        public string baslikENG { get; set; }
        public string aciklamaTR { get; set; }
        public string aciklamaENG { get; set; }
        public string link { get; set; }
        public string resim { get; set; }
    }
}
